apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.namePvc }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes}}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}